const Homeproduct = [
  {
    id: 1,
    Name: "product1",
    price: "26",
    image: "image/p1.webp",
    cat: "",
    type: "new",
  },
  {
    id: 2,
    Name: "product2",
    price: "75",
    image: "image/p2.webp",
    cat: "",
    type: "new",
  },
  {
    id: 3,
    Name: "product3",
    price: "182",
    image: "image/p3.webp",
    cat: "",
    type: "new",
  },
  {
    id: 4,
    Name: "product4",
    price: "93",
    image: "image/p4.webp",
    cat: "",
    type: "new",
  },
  {
    id: 5,
    Name: "product5",
    price: "66",
    image: "image/p5.webp",
    cat: "",
    type: "featured",
  },
  {
    id: 6,
    Name: "product6",
    price: "52",
    image: "image/p6.webp",
    cat: "",
    type: "featured",
  },
  {
    id: 7,
    Name: "product7",
    price: "68",
    image: "image/p7.webp",
    cat: "",
    type: "featured",
  },
  {
    id: 8,
    Name: "product8",
    price: "71",
    image: "image/p8.webp",
    cat: "",
    type: "featured",
  },
  {
    id: 9,
    Name: "product9",
    price: "241",
    image: "image/p9.jpg",
    cat: "",
    type: "top",
  },
  {
    id: 10,
    Name: "product10",
    price: "258",
    image: "image/p10.jpg",
    cat: "",
    type: "top",
  },
  {
    id: 11,
    Name: "product11",
    price: "179",
    image: "image/p11.jpg",
    cat: "",
    type: "top",
  },
  {
    id: 12,
    Name: "product12",
    price: "146",
    image: "image/p12.jpg",
    cat: "",
    type: "top",
  },
];
export default Homeproduct;
